name: twitter_api
version: 0.1.2
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/stefanuros/dartTwitterAPI
description: An easy way to authenticate and make requests to the Twitter API.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http:
  crypto: ^2.1.3
