name: twitter_api
version: 0.1.0
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/stefanuros/dartTwitterAPI
description: An easy way to authenticate and make requests to the Twitter API.

environment:
  sdk: '>=1.19.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  crypto: ^2.1.3
